[Definition]
failregex = ^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} INFO <HOST>:\d+ - \"GET (/.env|/phpmyadmin|/manager|/mcp|/sse|/SDK|/login|/portal|/robots|/.well-known|/setup|/app).*\" (403|404|429)$
ignoreregex =
